### ISSUE TITLE
[Bug] Auth token doesn't update

### ISSUE THREAD

**Issue by aliassan** [globe-and-citizen/cnc-portal#261]
## Description

**Describe the bug**
The auth token doesn't update and returns an old expired token so you're unable to login.

**To Reproduce**

1. Go to `backend/src/controllers/authController.ts`, ln 58
2. Change or set `expiresIn` value to '5s'
3. Logout of the app
4. Login and wait for 6s
5. Navigate to `APP_URL/login` without logging out
6. Try to login again

**Expected behavior**
It should reset the `authToken` and update to the new generated value

**Comment by hermannleboss** [comment]
I have this error when i try to login with the backend locally. 

do you have the same error ?
@aliassan 
![image](https://github.com/user-attachments/assets/ba1319da-df98-4e42-b945-f94933894826)

**Comment by aliassan** [comment]
No, I have 401 Unauthorized error in the front-end and jwt-expired error in the back-end

**Comment by hermannleboss** [comment]
The problem i have is because i'm not authenticated but i still have the token in the localstorage
![image](https://github.com/user-attachments/assets/36cac2d9-60a5-4d02-bd82-703fff4cb664)

And the old token is used for the next request. 

So i recieve in the SIWE request : /api/auth/siwe

```json
{
    "success": true,
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHg4MkZDMGQ4NGZBOUM2OTc0NTVjMkI5ZWE0MTZiYzAwYjkyOTNiZDZFIiwiaWF0IjoxNzIwODkxMzE3LCJleHAiOjE3MjA5Nzc3MTd9.ndC05KtXu3Nyfn5MU_6rvyyn9tWEnzobWdJwNxiTxy8"
}
```

But the token for authenticating the user fully is 
`Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHg4MkZDMGQ4NGZBOUM2OTc0NTVjMkI5ZWE0MTZiYzAwYjkyOTNiZDZFIiwiaWF0IjoxNzIwODg3OTgwLCJleHAiOjE3MjA5NzQzODB9._Q4ZIbDRs3MMaw2R9eabFMMmynLQyN9SuUkLMztP0TQ`

They are not simillar.

**Comment by hermannleboss** [comment]
But authentication need to be fully refactor to fix this issue.
